### ISSUE TITLE
Sync stops working at some point

### ISSUE THREAD

**Issue by lasselehtinen** [winnfsd/vagrant-winnfsd#45] opened 2015-03-30 10:44 UTC
This problem has occurred several times after I started using the plugin. It works for a while, but after a random time period the sync stops working completely. Meaning that file changes and new files do not appear on the Vagrant host. Doing a "vagrant reload" removes the problem for a while. I am running Windows 7 64-bit. See the attached screenshot for a sample. Is there any way to debug what might be causing this?

![30-3-2015 13-39-24](https://cloud.githubusercontent.com/assets/1290186/6894886/bfb16b38-d6e2-11e4-9eca-bf78f083f431.png)

**Comment by phazei** [comment] 2015-03-30 22:44
Yeah, that happens to me a lot as well

**Comment by lasselehtinen** [comment] 2015-03-31 07:19
I enabled debugging, but as it is the NFS server side but I could not find anything out of the ordinary. Strangest thing is that when this happens, I can still see the the NFS working just fine on the files that are already there.

**Comment by yannschepens** [comment] 2015-03-31 08:27
Hi,

I have some clue with this bugs. I'm working on.

Greetings,

Yann

2015-03-31 9:19 GMT+02:00 Lasse Lehtinen <notifications@github.com>:

> I enabled debugging, but as it is the NFS server side but I could not find
> anything out of the ordinary. Strangest thing is that when this happens, I
> can still see the the NFS working just fine on the files that are already
> there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GM-Alex/vagrant-winnfsd/issues/45#issuecomment-87971770>
> .
>



-- 
Yann Schepens

yann.schepens@gmail.com

**Comment by lasselehtinen** [comment] 2015-04-13 13:42
Any updates on this? This issue is still occurring daily for me and it is quite annoying having to vagrant reload constantly.

**Comment by yannschepens** [comment] 2015-04-13 14:08
Hi,

I have a very hard task to do on winnfsd, rewrite the file management. I
should correct this error, but I don't know when it's will be ready.

2015-04-13 15:42 GMT+02:00 Lasse Lehtinen <notifications@github.com>:

> Any updates on this? This issue is still occurring daily for me and it is
> quite annoying having to vagrant reload constantly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GM-Alex/vagrant-winnfsd/issues/45#issuecomment-92357150>
> .
>



-- 
Yann Schepens

yann.schepens@gmail.com

**Comment by ChrisCampbell88** [comment] 2015-04-14 07:37
This is also an issue for me, I've had to uninstall the plugin just to get a decent workflow. I look forward to the sync issue being fixed so I can use this again :)

**Comment by ChrisCampbell88** [comment] 2015-04-15 00:27
I also noticed that for me sync is usually lost when i change a file but it is still the same length, e.g. '#f00' to '#0f0', the file becomes out of sync. If i make a change elsewhere in the file and the length of the file changes, it comes back in to sync. Perhaps the issue is around sync looking at file length for changes rather than something better.

**Comment by tobikris** [comment] 2015-05-17 10:13
I can confirm this last mentioned bug of getting out of sync when the file length stays the same. It is somehow annyoing and would be nice if you could change this behavior.

**Comment by lasselehtinen** [comment] 2015-05-18 08:27
I also noticed that sometimes files created on the host never appear in the VM even though changes to the existing files are still in sync.

**Comment by kevinquillen** [comment] 2015-06-25 20:33
Could be this: https://bitbucket.org/jankowfsky/winnfsd/issue/7/winnfsd-doesnt-always-overwrite-files#comment-18134070

**Comment by marcharding** [comment] 2016-06-24 16:35
This is fixed with v1.2.0. See https://github.com/winnfsd/winnfsd/pull/21 for details.

**Closed by marcharding** 2016-06-24 16:35 UTC
